### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by FayasNoushad** [cyberboysumanjay/APIs#9]
If you are the application administrator, you can access the [diagnostic resources](https://sumanjay.scm.azurewebsites.net/detectors).

**Comment by FayasNoushad** [comment]
Please fix

**Comment by irlamplex** [comment]
> Please fix

I am getting the error below:

:( Application Error
If you are the application administrator, you can access the diagnostic resources.

**Comment by irlamplex** [comment]
I am getting the error below:

:( Application Error
If you are the application administrator, you can access the diagnostic resources.

**Comment by FayasNoushad** [comment]
> I am getting the error below:
> 
> :( Application Error
> If you are the application administrator, you can access the diagnostic resources.

Same error for me.

**Comment by cyberboysumanjay** [comment]
It seems Azure isn't happy with the API too 😞 
Anyways deployed API to Railway now 🥂 
Let me know if the issue is fixed now

**Comment by FayasNoushad** [comment]
Ohh! Its working sir.

**Comment by cyberboysumanjay** [comment]
Nice. 
Closing this issue now 👍🏻
